set(CPACK_GENERATOR ZIP)

set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY 0)
set(CPACK_INSTALL_CMAKE_PROJECTS
    "${CMAKE_BINARY_DIR}"
    "${PROJECT_NAME}"
    ALL
    /)
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")

include(CPack)
